In [16]:
def welcome_Massage():
    print("Hello User")

In [17]:
welcome_Massage()

Hello User

In [20]:
def welcome_Massage(user):
    print(f"Hello {user}")

In [21]:
welcome_Massage("Dip")

Hello Dip

In [23]:
def welcome_Massage(user='None'):
    print(f"Hello {user}")

In [24]:
welcome_Massage()

Hello None

In [26]:
def sum(a,b):
    sum=a+b
    print(f"Sum of {a} and {b} is {sum}")

In [28]:
sum(10,12)

Sum of 10 and 12 is 22

In [32]:
def adder(a,b):
    sum=a+b
    return sum

In [33]:
m=adder(10,10) * 5
print(m)

100

In [35]:
def adder(a,b):

    """
    add two numbers
    """

    sum=a+b
    return sum

In [36]:
m=adder(10,10) * 5
print(m)
help(adder)

100
Help on function adder in module __main__:

adder(a, b)
    add two numbers

## Different type of argument

In [37]:
def adder(a,b):
    print(f"{a},{b}")

adder(10,20)

10,20

In [38]:
def adder(*args):
    print(args)


adder(10,30,40,20)

(10, 30, 40, 20)

In [39]:
def adder(*args):
    for i in args:
        print(i)


adder(10,30,40,20)

10
30
40
20

### Keyword Argument

In [40]:
def adder(a,b,c):
    print(f"{a},{b},{c}")

adder(a=10,c=30,b=20)

10,20,30

In [46]:
def adder(**kwargs):
        print(kwargs)


adder(a=10,c=30,b=20)

{'a': 10, 'c': 30, 'b': 20}

In [47]:
def adder(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}:{value}")
      


adder(a=10,c=30,b=20)

a:10
c:30
b:20

### Return Type

In [48]:
def welcome_Massage():
    print("Hello User")

print(type(welcome_Massage()))

Hello User
<class 'NoneType'>

In [49]:
def adder(a,b):
    sum=a+b
    return sum
print(type(adder(10,20)))

<class 'int'>

In [50]:
def adder(a,b):
    sum=a+b
    return sum
print(type(adder(10.5,20.5)))

<class 'float'>

In [51]:
def welcome_Massage(user='None'):
    return f"Hello {user}"

print(type(welcome_Massage()))

<class 'str'>

In [54]:
def adder(a,b):
    
    return a,b
print(type(adder(10.5,20.5)))

x,y = adder(10.5,20.5)

print(x,y)
print(x)
print(y)

<class 'tuple'>
10.5 20.5
10.5
20.5

In [55]:
def adder(a,b):
    
    return [a,b]
print(type(adder(10.5,20.5)))

x,y = adder(10.5,20.5)

print(x,y)
print(x)
print(y)

<class 'list'>
10.5 20.5
10.5
20.5

## Iterator

In [3]:
S = {10,20,30,40,50}

S_iter = iter(S)


print(next(S_iter))
print(next(S_iter))
print(next(S_iter))
print(next(S_iter))

50
20
40
10

## Genaratror

In [3]:
lst = [x for x in range(500)]

def data_loader(chunk_size,lst):
    for i in range(0,len(lst),chunk_size):
        yield lst[i:i+chunk_size]

x= data_loader(5,lst)

print(type(x))
print(x)


print(next(x))
print(next(x))

<class 'generator'>
<generator object data_loader at 0x0000013D95945030>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

## Lambda Function

In [6]:
import pandas as pd

df = pd.DataFrame({'temperature (F)':[32,212,98.6,68]})
df
df['temperature (c)']=df['temperature (F)'].apply(lambda x : (x-32)*5/9)
df

   temperature (F)  temperature (c)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [10]:
import pandas as pd

df = pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})

df

df['A'] = df['A'].map(lambda x:x ** 0.5)
df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8